
import React, { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { 
  BookOpen, 
  Edit3, 
  Save, 
  CheckCircle, 
  Clock,
  Download
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface Question {
  id: number;
  question: string;
  category: string;
  difficulty: string;
  description: string;
}

interface QuestionCardProps {
  question: Question;
}

export const QuestionCard = ({ question }: QuestionCardProps) => {
  const [answer, setAnswer] = useState('');
  const [isAnswering, setIsAnswering] = useState(false);
  const [isSaved, setIsSaved] = useState(false);
  const { toast } = useToast();

  const downloadAnswerAsText = () => {
    if (!answer.trim()) {
      toast({
        title: "No answer to download",
        description: "Please write an answer before downloading.",
        variant: "destructive"
      });
      return;
    }

    // Get user details from localStorage or use guest info
    const userId = localStorage.getItem('userId') || 'guest';
    const userName = localStorage.getItem('userName') || 'Guest User';
    const userEmail = localStorage.getItem('userEmail') || 'No email provided';
    
    // Create the text content
    const textContent = `
INTERVIEW QUESTION ANSWER
========================

User Details:
- User ID: ${userId}
- Name: ${userName}
- Email: ${userEmail}
- Date: ${new Date().toLocaleString()}

Question Details:
- ID: ${question.id}
- Category: ${question.category}
- Difficulty: ${question.difficulty}
- Question: ${question.question}
- Description: ${question.description}

Answer:
${answer}

Generated by Interview-Wiz-Guide
    `.trim();

    // Create and download the file
    const blob = new Blob([textContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    
    // Create filename with question ID and timestamp
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    link.download = `interview-answer-q${question.id}-${timestamp}.txt`;
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    toast({
      title: "Answer downloaded!",
      description: "Your answer has been saved to your downloads folder.",
    });
  };

  const handleSaveAnswer = async () => {
    if (!answer.trim()) {
      toast({
        title: "No answer provided",
        description: "Please write an answer before saving.",
        variant: "destructive"
      });
      return;
    }

    // Save to local database via API
    try {
      const response = await fetch('http://localhost:8000/api/answers', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          questionId: question.id,
          answer: answer,
          userId: localStorage.getItem('userId') || 'guest'
        }),
      });

      if (response.ok) {
        setIsSaved(true);
        toast({
          title: "Answer saved!",
          description: "Your answer has been saved for review.",
        });
      } else {
        toast({
          title: "Failed to save",
          description: "Your answer couldn't be saved. Please try again.",
          variant: "destructive"
        });
      }
    } catch (error) {
      console.error('Error saving answer:', error);
      // Fallback to local storage if API is not available yet
      console.log('Saving answer:', { questionId: question.id, answer });
      setIsSaved(true);
      toast({
        title: "Answer saved locally!",
        description: "Your answer has been saved for review.",
      });
    }
  };

  const getDifficultyColor = (difficulty: string) => {
    switch (difficulty.toLowerCase()) {
      case 'easy': return 'bg-green-100 text-green-800';
      case 'medium': return 'bg-yellow-100 text-yellow-800';
      case 'hard': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  return (
    <Card className="p-6 hover:shadow-lg transition-all duration-300">
      <div className="flex items-start justify-between mb-4">
        <div className="flex items-start space-x-3">
          <div className="flex items-center justify-center w-10 h-10 bg-blue-100 rounded-lg">
            <BookOpen className="h-5 w-5 text-blue-600" />
          </div>
          <div className="flex-1">
            <div className="flex items-center space-x-2 mb-2">
              <Badge variant="outline" className="text-xs">
                {question.category}
              </Badge>
              <Badge className={`text-xs ${getDifficultyColor(question.difficulty)}`}>
                {question.difficulty}
              </Badge>
            </div>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">
              {question.question}
            </h3>
            <p className="text-sm text-gray-600">
              {question.description}
            </p>
          </div>
        </div>
        
        <div className="flex items-center space-x-2">
          {isSaved && (
            <CheckCircle className="h-5 w-5 text-green-600" />
          )}
          <Clock className="h-4 w-4 text-gray-400" />
        </div>
      </div>

      {/* Answer Section */}
      <div className="mt-6">
        {!isAnswering ? (
          <Button 
            onClick={() => setIsAnswering(true)}
            className="w-full bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700"
          >
            <Edit3 className="h-4 w-4 mr-2" />
            Write Your Answer
          </Button>
        ) : (
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Your Answer
              </label>
              <Textarea
                value={answer}
                onChange={(e) => setAnswer(e.target.value)}
                placeholder="Type your answer here... Be detailed and explain your reasoning."
                className="min-h-[150px]"
              />
            </div>
            
            <div className="flex items-center justify-between">
              <Button 
                variant="outline" 
                onClick={() => setIsAnswering(false)}
              >
                Cancel
              </Button>
              
              <div className="flex space-x-2">
                <Button 
                  variant="outline"
                  onClick={downloadAnswerAsText}
                  disabled={!answer.trim()}
                >
                  <Download className="h-4 w-4 mr-2" />
                  Download
                </Button>
                
                <Button 
                  onClick={handleSaveAnswer}
                  disabled={!answer.trim()}
                >
                  <Save className="h-4 w-4 mr-2" />
                  Save Answer
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>
    </Card>
  );
};
